/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create options (`createClient` argument; see `node/contract.md`). */
export interface CreateOptions {
  token: string
  intents: number
  cache: string
  sharding: string
}
/**
 * Create a client; returns its numeric handle.
 *
 * The token is kept in Rust as `SecretString` and is never readable back.
 * Only `"auto"` sharding is accepted in M3.
 */
export declare function createClient(options: CreateOptions): number
/**
 * Test-only client pointed at mock transports (never production).
 *
 * Same contract as `createClient`, plus mock base URLs. Not for live use.
 */
export declare function createTestClient(options: CreateOptions, restBase: string, gatewayBase: string): number
/** Subscribe event kinds with a listener (replaces any previous one). */
export declare function subscribe(handle: number, kinds: Array<string>, listener: (...args: any[]) => any): void
/** Clear the subscription (releases the listener). */
export declare function unsubscribe(handle: number): void
/** Login with 30s READY discipline (production or mock gateway per client). */
export declare function login(handle: number): Promise<void>
/** Fetch one page of channel history (clamp: `0` maps to `1`). */
export declare function fetchPage(handle: number, channelId: string, limit: number): Promise<Array<MessageSnapshot>>
/**
 * Fetch coarse pages eagerly with a binding-held cursor.
 *
 * Stops at the first short page or after 10 pages, whichever comes first.
 * One array crossing per page; no per-item iteration, no retained iterator.
 * (`Page` in the contract is a docs alias for one `Message[]` element.)
 */
export declare function streamPages(handle: number, channelId: string, limit: number): Promise<Array<Array<MessageSnapshot>>>
/** Synchronous health numbers. */
export declare function getHealth(handle: number): HealthSnapshot
/** Synchronous per-shard latencies. */
export declare function getLatencies(handle: number): Array<LatencyRow>
/** Synchronous uptime in milliseconds (`f64`: JS numbers cannot hold `u64`). */
export declare function getUptimeMs(handle: number): number
/** Synchronous cache numbers. */
export declare function getCacheStats(handle: number): CacheSnapshot
/** Pure ed25519 webhook verification (bytes only, fail-closed). */
export declare function verifyWebhook(publicKeyHex: string, timestamp: string, body: Buffer, sigHex: string): void
/**
 * Close a client: mark closed, drop the queue, release the listener,
 * forget the handle. A second close of the same handle rejects
 * `unknown-handle` (the id no longer maps to anything).
 */
export declare function close(handle: number): Promise<void>
/** One message snapshot (see `node/contract.md`). */
export interface MessageSnapshot {
  id: string
  channelId: string
  authorId: string
  content: string
  timestamp: string
}
/** Health numbers for `getHealth` (see `node/contract.md`). */
export interface HealthSnapshot {
  ready: boolean
  shards: number
  guildsCached: number
  eventsDropped: number
}
/**
 * One shard latency row for `getLatencies` (milliseconds as `f64`: JS
 * numbers cannot hold `u64` exactly).
 */
export interface LatencyRow {
  shard: number
  total: number
  latencyMs: number
}
/** Cache numbers for `getCacheStats`. */
export interface CacheSnapshot {
  hitRatio: number
  guilds: number
  channels: number
  messages: number
}
/** Binding version (crate version of `rivulus-node`). Smoke-test surface. */
export declare function version(): string
